# Generated by Django 4.0.3 on 2022-04-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
