# Generated by Django 4.0.3 on 2022-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro1', '0002_employee_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='', max_length=130),
        ),
    ]
