# Generated by Django 4.0.3 on 2022-04-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro1', '0003_employee_phone_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default='', max_length=130),
        ),
    ]
