# Generated by Django 4.0.3 on 2022-04-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro1', '0005_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(blank=True, max_length=10),
        ),
    ]
