# Generated by Django 4.0.3 on 2022-04-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypro1', '0006_alter_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
